name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2026-22.04-py314

    steps:
    - uses: actions/checkout@v4

    # prevents Dubious Ownership err
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +777 ./gradlew
      # CHANGE THIS TO DIRECTORY PATH
      working-directory: ./2026

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew build
      # CHANGE THIS TO DIRECTORY PATH
      working-directory: ./2026
